package isilimageprocessing;

import CImage.*;
import CImage.Exceptions.*;
import CImage.Observers.*;
import CImage.Observers.Events.*;
import ImageProcessing.Complexe.MatriceComplexe;
import ImageProcessing.Fourier.Fourier;
import ImageProcessing.Histogramme.Histogramme;
import ImageProcessing.Lineaire.FiltrageLineaireGlobal;
import ImageProcessing.Lineaire.FiltrageLineaireLocal;
import ImageProcessing.NonLineaire.MorphoElementaire;
import ImageProcessing.NonLineaire.MorphoComplexe;
import isilimageprocessing.Dialogues.*;
import isilimageprocessing.SlotData;
import isilimageprocessing.SlotReceiver;
import java.awt.*;
import java.awt.datatransfer.*;
import java.awt.event.MouseMotionAdapter;
import java.awt.event.MouseEvent;
import java.io.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;
import javax.swing.TransferHandler;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.ValueAxis;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author  HP_Propri�taire
 */
public class IsilImageProcessing extends javax.swing.JFrame implements ClicListener,SelectLigneListener,SelectRectListener,SelectRectFillListener,SelectCercleListener,SelectCercleFillListener 
{
    private CImageRGB imageRGB;
    private CImageNG  imageNG;
    private javax.swing.JMenu jMenuFiltrageLineaire;
    private javax.swing.JMenu jMenuTraitementNonLineaire;
    private javax.swing.JMenu jMenuContours;
    private javax.swing.JMenu jMenuSeuillage;
    private javax.swing.JMenu jMenuApplications;

    // --- Système de slots ---
    private static final int   NB_SLOTS       = 4;
    private CImageNG[]         slotImagesNG    = new CImageNG[NB_SLOTS];
    private CImageRGB[]        slotImagesRGB   = new CImageRGB[NB_SLOTS];
    private String[]           slotLabels      = new String[NB_SLOTS];
    private JLabelBeanCImage[] slotObservers   = new JLabelBeanCImage[NB_SLOTS];
    private JPanel[]           slotPanels      = new JPanel[NB_SLOTS];
    private JScrollPane[]      slotScrollPanes = new JScrollPane[NB_SLOTS];
    private JLabel[]           slotTitleLabels = new JLabel[NB_SLOTS];
    private int                activeSlot      = 0;

    private JLabelBeanCImage observer;
    private Color couleurPinceauRGB;
    private int   couleurPinceauNG;
    
    /** Creates new form TestCImage2 */
    public IsilImageProcessing() 
    {
        initComponents();
        
        imageRGB = null;
        imageNG  = null;
        
        observer = new JLabelBeanCImage();
        observer.addClicListener(this);
        observer.addSelectLigneListener(this);
        observer.addSelectRectListener(this);
        observer.addSelectRectFillListener(this);
        observer.addSelectCercleListener(this);
        observer.addSelectCercleFillListener(this);
        observer.setMode(JLabelBeanCImage.INACTIF);
        jScrollPane.setViewportView(observer);
        
        jMenuDessiner.setEnabled(false);
        jMenuFourier.setEnabled(false);
        jMenuHistogramme.setEnabled(false);
        
        couleurPinceauRGB = Color.BLACK;
        couleurPinceauNG = 0;

        setupFiltrageMenu();
        setupMorphoMenu();
        setupContoursMenu();
        setupSeuillageMenu();
        setupApplicationsMenu();
        setupSlots();
        setupHistogrammeExtraMenu();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupDessiner = new javax.swing.ButtonGroup();
        jScrollPane = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuImage = new javax.swing.JMenu();
        jMenuNouvelle = new javax.swing.JMenu();
        jMenuItemNouvelleRGB = new javax.swing.JMenuItem();
        jMenuItemNouvelleNG = new javax.swing.JMenuItem();
        jMenuOuvrir = new javax.swing.JMenu();
        jMenuItemOuvrirRGB = new javax.swing.JMenuItem();
        jMenuItemOuvrirNG = new javax.swing.JMenuItem();
        jMenuItemEnregistrerSous = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuQuitter = new javax.swing.JMenuItem();
        jMenuDessiner = new javax.swing.JMenu();
        jMenuItemCouleurPinceau = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        jCheckBoxMenuItemDessinerPixel = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemDessinerLigne = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemDessinerRectangle = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemDessinerRectanglePlein = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemDessinerCercle = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemDessinerCerclePlein = new javax.swing.JCheckBoxMenuItem();
        jMenuFourier = new javax.swing.JMenu();
        jMenuFourierAfficher = new javax.swing.JMenu();
        jMenuItemFourierAfficherModule = new javax.swing.JMenuItem();
        jMenuItemFourierAfficherPhase = new javax.swing.JMenuItem();
        jMenuItemFourierAfficherPartieReelle = new javax.swing.JMenuItem();
        jMenuItemFourierAfficherPartieImaginaire = new javax.swing.JMenuItem();
        jMenuHistogramme = new javax.swing.JMenu();
        jMenuHistogrammeAfficher = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Isil Image Processing");

        jMenuImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Net 13_p1.jpg"))); // NOI18N
        jMenuImage.setText("Image");

        jMenuNouvelle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/File 65_p3.jpg"))); // NOI18N
        jMenuNouvelle.setText("Nouvelle");

        jMenuItemNouvelleRGB.setText("Image RGB");
        jMenuItemNouvelleRGB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNouvelleRGBActionPerformed(evt);
            }
        });
        jMenuNouvelle.add(jMenuItemNouvelleRGB);

        jMenuItemNouvelleNG.setText("Image NG");
        jMenuItemNouvelleNG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNouvelleNGActionPerformed(evt);
            }
        });
        jMenuNouvelle.add(jMenuItemNouvelleNG);

        jMenuImage.add(jMenuNouvelle);

        jMenuOuvrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Folder 036_p3.jpg"))); // NOI18N
        jMenuOuvrir.setText("Ouvrir");

        jMenuItemOuvrirRGB.setText("Image RGB");
        jMenuItemOuvrirRGB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOuvrirRGBActionPerformed(evt);
            }
        });
        jMenuOuvrir.add(jMenuItemOuvrirRGB);

        jMenuItemOuvrirNG.setText("Image NG");
        jMenuItemOuvrirNG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOuvrirNGActionPerformed(evt);
            }
        });
        jMenuOuvrir.add(jMenuItemOuvrirNG);

        jMenuImage.add(jMenuOuvrir);

        jMenuItemEnregistrerSous.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/DD 27_p3.jpg"))); // NOI18N
        jMenuItemEnregistrerSous.setText("Enregistrer sous...");
        jMenuItemEnregistrerSous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEnregistrerSousActionPerformed(evt);
            }
        });
        jMenuImage.add(jMenuItemEnregistrerSous);
        jMenuImage.add(jSeparator1);

        jMenuQuitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/CP 59_p3.jpg"))); // NOI18N
        jMenuQuitter.setText("Quitter");
        jMenuQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuQuitterActionPerformed(evt);
            }
        });
        jMenuImage.add(jMenuQuitter);

        jMenuBar1.add(jMenuImage);

        jMenuDessiner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Display 28_p1.jpg"))); // NOI18N
        jMenuDessiner.setText("Dessiner");

        jMenuItemCouleurPinceau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Display 14_p3.jpg"))); // NOI18N
        jMenuItemCouleurPinceau.setText("Couleur");
        jMenuItemCouleurPinceau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCouleurPinceauActionPerformed(evt);
            }
        });
        jMenuDessiner.add(jMenuItemCouleurPinceau);
        jMenuDessiner.add(jSeparator2);

        jCheckBoxMenuItemDessinerPixel.setText("Pixel");
        jCheckBoxMenuItemDessinerPixel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemDessinerPixelActionPerformed(evt);
            }
        });
        jMenuDessiner.add(jCheckBoxMenuItemDessinerPixel);

        jCheckBoxMenuItemDessinerLigne.setText("Ligne");
        jCheckBoxMenuItemDessinerLigne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemDessinerLigneActionPerformed(evt);
            }
        });
        jMenuDessiner.add(jCheckBoxMenuItemDessinerLigne);

        jCheckBoxMenuItemDessinerRectangle.setText("Rectangle");
        jCheckBoxMenuItemDessinerRectangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemDessinerRectangleActionPerformed(evt);
            }
        });
        jMenuDessiner.add(jCheckBoxMenuItemDessinerRectangle);

        jCheckBoxMenuItemDessinerRectanglePlein.setText("Rectangle plein");
        jCheckBoxMenuItemDessinerRectanglePlein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemDessinerRectanglePleinActionPerformed(evt);
            }
        });
        jMenuDessiner.add(jCheckBoxMenuItemDessinerRectanglePlein);

        jCheckBoxMenuItemDessinerCercle.setText("Cercle");
        jCheckBoxMenuItemDessinerCercle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemDessinerCercleActionPerformed(evt);
            }
        });
        jMenuDessiner.add(jCheckBoxMenuItemDessinerCercle);

        jCheckBoxMenuItemDessinerCerclePlein.setText("Cercle plein");
        jCheckBoxMenuItemDessinerCerclePlein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemDessinerCerclePleinActionPerformed(evt);
            }
        });
        jMenuDessiner.add(jCheckBoxMenuItemDessinerCerclePlein);

        jMenuBar1.add(jMenuDessiner);

        jMenuFourier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/CP 51_p1.jpg"))); // NOI18N
        jMenuFourier.setText("Fourier");

        jMenuFourierAfficher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/CP 51_p3.jpg"))); // NOI18N
        jMenuFourierAfficher.setText("Afficher");

        jMenuItemFourierAfficherModule.setText("Module");
        jMenuItemFourierAfficherModule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFourierAfficherModuleActionPerformed(evt);
            }
        });
        jMenuFourierAfficher.add(jMenuItemFourierAfficherModule);

        jMenuItemFourierAfficherPhase.setText("Phase");
        jMenuItemFourierAfficherPhase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFourierAfficherPhaseActionPerformed(evt);
            }
        });
        jMenuFourierAfficher.add(jMenuItemFourierAfficherPhase);

        jMenuItemFourierAfficherPartieReelle.setText("Partie Reelle");
        jMenuItemFourierAfficherPartieReelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFourierAfficherPartieReelleActionPerformed(evt);
            }
        });
        jMenuFourierAfficher.add(jMenuItemFourierAfficherPartieReelle);

        jMenuItemFourierAfficherPartieImaginaire.setText("Partie Imaginaire");
        jMenuItemFourierAfficherPartieImaginaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFourierAfficherPartieImaginaireActionPerformed(evt);
            }
        });
        jMenuFourierAfficher.add(jMenuItemFourierAfficherPartieImaginaire);

        jMenuFourier.add(jMenuFourierAfficher);

        jMenuBar1.add(jMenuFourier);

        jMenuHistogramme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/report_48_hot.jpg"))); // NOI18N
        jMenuHistogramme.setText("Histogramme");

        jMenuHistogrammeAfficher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/report_32_hot.jpg"))); // NOI18N
        jMenuHistogrammeAfficher.setText("Afficher les histogrammes");
        jMenuHistogrammeAfficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuHistogrammeAfficherActionPerformed(evt);
            }
        });
        jMenuHistogramme.add(jMenuHistogrammeAfficher);

        jMenuBar1.add(jMenuHistogramme);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(500, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuHistogrammeAfficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuHistogrammeAfficherActionPerformed
        int histo[];
        try 
        {
            int f_int[][] = imageNG.getMatrice();
            histo = Histogramme.Histogramme256(f_int);
        } 
        catch (CImageNGException ex) 
        {
            System.out.println("Erreur CImageNG : " + ex.getMessage());
            return;
        }
        
        // Cr�ation du dataset
        XYSeries serie = new XYSeries("Histo");
        for(int i=0 ; i<256 ; i++) serie.add(i,histo[i]);
        XYSeriesCollection dataset = new XYSeriesCollection();
        dataset.addSeries(serie);
        
        // Creation du chart
        JFreeChart chart = ChartFactory.createHistogram("Histogramme","Niveaux de gris","Nombre de pixels",dataset,PlotOrientation.VERTICAL,false,false,false);

        XYPlot plot = (XYPlot)chart.getXYPlot();
        ValueAxis axeX = plot.getDomainAxis();
        axeX.setRange(0,255);
        plot.setDomainAxis(axeX);
        
        // creation d'une frame
        ChartFrame frame = new ChartFrame("Histogramme de l'image",chart);
        frame.pack();
        frame.setVisible(true);
    }//GEN-LAST:event_jMenuHistogrammeAfficherActionPerformed

    private void activeMenusNG()
    {
        jMenuDessiner.setEnabled(true);
        jMenuFourier.setEnabled(true);
        jMenuHistogramme.setEnabled(true);
        jMenuFiltrageLineaire.setEnabled(true);
        jMenuTraitementNonLineaire.setEnabled(true);
        jMenuContours.setEnabled(true);
        jMenuSeuillage.setEnabled(true);
    }

    private void activeMenusRGB()
    {
        jMenuDessiner.setEnabled(true);
        jMenuFourier.setEnabled(false);
        jMenuHistogramme.setEnabled(false);
        jMenuFiltrageLineaire.setEnabled(false);
        jMenuTraitementNonLineaire.setEnabled(false);
        jMenuContours.setEnabled(false);
        jMenuSeuillage.setEnabled(false);
    }
    
    private void jCheckBoxMenuItemDessinerCerclePleinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemDessinerCerclePleinActionPerformed
        if (!jCheckBoxMenuItemDessinerCerclePlein.isSelected()) observer.setMode(JLabelBeanCImage.INACTIF);
        else
        {
            jCheckBoxMenuItemDessinerPixel.setSelected(false);
            jCheckBoxMenuItemDessinerLigne.setSelected(false);
            jCheckBoxMenuItemDessinerRectangle.setSelected(false);
            jCheckBoxMenuItemDessinerRectanglePlein.setSelected(false);
            jCheckBoxMenuItemDessinerCercle.setSelected(false);
            jCheckBoxMenuItemDessinerCerclePlein.setSelected(true);
            observer.setMode(JLabelBeanCImage.SELECT_CERCLE_FILL);
        }
    }//GEN-LAST:event_jCheckBoxMenuItemDessinerCerclePleinActionPerformed

    private void jCheckBoxMenuItemDessinerCercleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemDessinerCercleActionPerformed
        if (!jCheckBoxMenuItemDessinerCercle.isSelected()) observer.setMode(JLabelBeanCImage.INACTIF);
        else
        {
            jCheckBoxMenuItemDessinerPixel.setSelected(false);
            jCheckBoxMenuItemDessinerLigne.setSelected(false);
            jCheckBoxMenuItemDessinerRectangle.setSelected(false);
            jCheckBoxMenuItemDessinerRectanglePlein.setSelected(false);
            jCheckBoxMenuItemDessinerCercle.setSelected(true);
            jCheckBoxMenuItemDessinerCerclePlein.setSelected(false);
            observer.setMode(JLabelBeanCImage.SELECT_CERCLE);
        }
    }//GEN-LAST:event_jCheckBoxMenuItemDessinerCercleActionPerformed

    private void jMenuItemFourierAfficherPartieImaginaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFourierAfficherPartieImaginaireActionPerformed
        try 
        {
            int f_int[][] = imageNG.getMatrice();
            double f[][] = new double[imageNG.getLargeur()][imageNG.getHauteur()];
            for(int i=0 ; i<imageNG.getLargeur() ; i++)
                for(int j=0 ; j<imageNG.getHauteur() ; j++) f[i][j] = (double)(f_int[i][j]);
            
            System.out.println("Debut Fourier");
            MatriceComplexe fourier = Fourier.Fourier2D(f);
            System.out.println("Fin Fourier");
            fourier = Fourier.decroise(fourier);
            double partieImaginaire[][] = fourier.getPartieImaginaire();
            
            JDialogAfficheMatriceDouble dialog = new JDialogAfficheMatriceDouble(this,true,partieImaginaire,"Fourier : Affichage de la partie imaginaire");
            dialog.setVisible(true);
        } 
        catch (CImageNGException ex) 
        {
            System.out.println("Erreur CImageNG : " + ex.getMessage());
        }
    }//GEN-LAST:event_jMenuItemFourierAfficherPartieImaginaireActionPerformed

    private void jMenuItemFourierAfficherPartieReelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFourierAfficherPartieReelleActionPerformed
        try 
        {
            int f_int[][] = imageNG.getMatrice();
            double f[][] = new double[imageNG.getLargeur()][imageNG.getHauteur()];
            for(int i=0 ; i<imageNG.getLargeur() ; i++)
                for(int j=0 ; j<imageNG.getHauteur() ; j++) f[i][j] = (double)(f_int[i][j]);
            
            System.out.println("Debut Fourier");
            MatriceComplexe fourier = Fourier.Fourier2D(f);
            System.out.println("Fin Fourier");
            fourier = Fourier.decroise(fourier);
            double partieReelle[][] = fourier.getPartieReelle();
            
            JDialogAfficheMatriceDouble dialog = new JDialogAfficheMatriceDouble(this,true,partieReelle,"Fourier : Affichage de la partie reelle");
            dialog.setVisible(true);
        } 
        catch (CImageNGException ex) 
        {
            System.out.println("Erreur CImageNG : " + ex.getMessage());
        }

    }//GEN-LAST:event_jMenuItemFourierAfficherPartieReelleActionPerformed

    private void jMenuItemFourierAfficherPhaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFourierAfficherPhaseActionPerformed
        try 
        {
            int f_int[][] = imageNG.getMatrice();
            double f[][] = new double[imageNG.getLargeur()][imageNG.getHauteur()];
            for(int i=0 ; i<imageNG.getLargeur() ; i++)
                for(int j=0 ; j<imageNG.getHauteur() ; j++) f[i][j] = (double)(f_int[i][j]);
            
            System.out.println("Debut Fourier");
            MatriceComplexe fourier = Fourier.Fourier2D(f);
            System.out.println("Fin Fourier");
            fourier = Fourier.decroise(fourier);
            double phase[][] = fourier.getPhase();
            
            JDialogAfficheMatriceDouble dialog = new JDialogAfficheMatriceDouble(this,true,phase,"Fourier : Affichage de la phase");
            dialog.setVisible(true);
        } 
        catch (CImageNGException ex) 
        {
            System.out.println("Erreur CImageNG : " + ex.getMessage());
        }

    }//GEN-LAST:event_jMenuItemFourierAfficherPhaseActionPerformed

    private void jMenuItemFourierAfficherModuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFourierAfficherModuleActionPerformed
        try 
        {
            int f_int[][] = imageNG.getMatrice();
            double f[][] = new double[imageNG.getLargeur()][imageNG.getHauteur()];
            for(int i=0 ; i<imageNG.getLargeur() ; i++)
                for(int j=0 ; j<imageNG.getHauteur() ; j++) f[i][j] = (double)(f_int[i][j]);
            
            System.out.println("Debut Fourier");
            MatriceComplexe fourier = Fourier.Fourier2D(f);
            System.out.println("Fin Fourier");
            fourier = Fourier.decroise(fourier);
            double module[][] = fourier.getModule();
            
            JDialogAfficheMatriceDouble dialog = new JDialogAfficheMatriceDouble(this,true,module,"Fourier : Affichage du module");
            dialog.setVisible(true);
        } 
        catch (CImageNGException ex) 
        {
            System.out.println("Erreur CImageNG : " + ex.getMessage());
        }
    }//GEN-LAST:event_jMenuItemFourierAfficherModuleActionPerformed

    private void jCheckBoxMenuItemDessinerPixelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemDessinerPixelActionPerformed
        if (!jCheckBoxMenuItemDessinerPixel.isSelected()) observer.setMode(JLabelBeanCImage.INACTIF);
        else
        {
            jCheckBoxMenuItemDessinerPixel.setSelected(true);
            jCheckBoxMenuItemDessinerLigne.setSelected(false);
            jCheckBoxMenuItemDessinerRectangle.setSelected(false);
            jCheckBoxMenuItemDessinerRectanglePlein.setSelected(false);
            jCheckBoxMenuItemDessinerCercle.setSelected(false);
            jCheckBoxMenuItemDessinerCerclePlein.setSelected(false);
            observer.setMode(JLabelBeanCImage.CLIC);
        }
    }//GEN-LAST:event_jCheckBoxMenuItemDessinerPixelActionPerformed

    private void jMenuItemEnregistrerSousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEnregistrerSousActionPerformed
        JFileChooser choix = new JFileChooser();
	File fichier;
			
	choix.setCurrentDirectory(new File ("."));
	if (choix.showOpenDialog(null) == JFileChooser.APPROVE_OPTION)
	{
            fichier = choix.getSelectedFile();
            if (fichier != null)
            {
                try 
                {
                    if (imageRGB != null) imageRGB.enregistreFormatPNG(fichier);
                    if (imageNG != null) imageNG.enregistreFormatPNG(fichier);
                } 
                catch (IOException ex) 
                {
                    System.err.println("Erreur I/O : " + ex.getMessage());
                }
            }
	}
    }//GEN-LAST:event_jMenuItemEnregistrerSousActionPerformed

    private void jMenuItemOuvrirNGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOuvrirNGActionPerformed
        JFileChooser choix = new JFileChooser();
	File fichier;
			
	choix.setCurrentDirectory(new File ("."));
	if (choix.showOpenDialog(null) == JFileChooser.APPROVE_OPTION)
	{
            fichier = choix.getSelectedFile();
            if (fichier != null)
            {
                try 
                {
                    imageNG = new CImageNG(fichier);
                    slotImagesNG[activeSlot]  = imageNG;
                    slotImagesRGB[activeSlot] = null;
                    slotLabels[activeSlot]    = fichier.getName();
                    slotTitleLabels[activeSlot].setText(fichier.getName());
                    observer.setCImage(imageNG);
                    imageRGB = null;
                    activeMenusNG();
                } 
                catch (IOException ex) 
                {
                    System.err.println("Erreur I/O : " + ex.getMessage());
                }
            }
	}
    }//GEN-LAST:event_jMenuItemOuvrirNGActionPerformed

    private void jMenuItemNouvelleNGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNouvelleNGActionPerformed
        JDialogNouvelleCImageNG dialog = new JDialogNouvelleCImageNG(this,true);
        dialog.setVisible(true);
        imageNG = dialog.getCImageNG();
        if (imageNG == null) return;
        slotImagesNG[activeSlot]  = imageNG;
        slotImagesRGB[activeSlot] = null;
        slotLabels[activeSlot]    = "Nouvelle NG";
        slotTitleLabels[activeSlot].setText("Nouvelle NG");
        observer.setCImage(imageNG);
        imageRGB = null;
        activeMenusNG();
    }//GEN-LAST:event_jMenuItemNouvelleNGActionPerformed

    private void jMenuItemCouleurPinceauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCouleurPinceauActionPerformed
        if (imageRGB != null)
        {
            Color newC = JColorChooser.showDialog(this,"Couleur du pinceau",couleurPinceauRGB);
            if (newC != null) couleurPinceauRGB = newC;
            observer.setCouleurPinceau(couleurPinceauRGB);
        }
        
        if (imageNG != null)
        {
            JDialogChoixCouleurNG dialog = new JDialogChoixCouleurNG(this,true,couleurPinceauNG);
            dialog.setVisible(true);
            couleurPinceauNG = dialog.getCouleur();
        }
    }//GEN-LAST:event_jMenuItemCouleurPinceauActionPerformed

    private void jCheckBoxMenuItemDessinerRectanglePleinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemDessinerRectanglePleinActionPerformed
        if (!jCheckBoxMenuItemDessinerRectanglePlein.isSelected()) observer.setMode(JLabelBeanCImage.INACTIF);
        else
        {
            jCheckBoxMenuItemDessinerPixel.setSelected(false);
            jCheckBoxMenuItemDessinerLigne.setSelected(false);
            jCheckBoxMenuItemDessinerRectangle.setSelected(false);
            jCheckBoxMenuItemDessinerRectanglePlein.setSelected(true);
            jCheckBoxMenuItemDessinerCercle.setSelected(false);
            jCheckBoxMenuItemDessinerCerclePlein.setSelected(false);
            observer.setMode(JLabelBeanCImage.SELECT_RECT_FILL);
        }
    }//GEN-LAST:event_jCheckBoxMenuItemDessinerRectanglePleinActionPerformed

    private void jCheckBoxMenuItemDessinerRectangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemDessinerRectangleActionPerformed
        if (!jCheckBoxMenuItemDessinerRectangle.isSelected()) observer.setMode(JLabelBeanCImage.INACTIF);
        else
        {
            jCheckBoxMenuItemDessinerPixel.setSelected(false);
            jCheckBoxMenuItemDessinerLigne.setSelected(false);
            jCheckBoxMenuItemDessinerRectangle.setSelected(true);
            jCheckBoxMenuItemDessinerRectanglePlein.setSelected(false);
            jCheckBoxMenuItemDessinerCercle.setSelected(false);
            jCheckBoxMenuItemDessinerCerclePlein.setSelected(false);
            observer.setMode(JLabelBeanCImage.SELECT_RECT);
        }
    }//GEN-LAST:event_jCheckBoxMenuItemDessinerRectangleActionPerformed

    private void jCheckBoxMenuItemDessinerLigneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemDessinerLigneActionPerformed
        if (!jCheckBoxMenuItemDessinerLigne.isSelected()) observer.setMode(JLabelBeanCImage.INACTIF);
        else
        {
            jCheckBoxMenuItemDessinerPixel.setSelected(false);
            jCheckBoxMenuItemDessinerLigne.setSelected(true);
            jCheckBoxMenuItemDessinerRectangle.setSelected(false);
            jCheckBoxMenuItemDessinerRectanglePlein.setSelected(false);
            jCheckBoxMenuItemDessinerCercle.setSelected(false);
            jCheckBoxMenuItemDessinerCerclePlein.setSelected(false);
            observer.setMode(JLabelBeanCImage.SELECT_LIGNE);
        }
    }//GEN-LAST:event_jCheckBoxMenuItemDessinerLigneActionPerformed

    private void jMenuItemNouvelleRGBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNouvelleRGBActionPerformed
        JDialogNouvelleCImageRGB dialog = new JDialogNouvelleCImageRGB(this,true);
        dialog.setVisible(true);
        imageRGB = dialog.getCImageRGB();
        if (imageRGB == null) return;
        slotImagesRGB[activeSlot] = imageRGB;
        slotImagesNG[activeSlot]  = null;
        slotLabels[activeSlot]    = "Nouvelle RGB";
        slotTitleLabels[activeSlot].setText("Nouvelle RGB");
        observer.setCImage(imageRGB);
        imageNG = null;
        activeMenusRGB();
    }//GEN-LAST:event_jMenuItemNouvelleRGBActionPerformed

    private void jMenuQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuQuitterActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuQuitterActionPerformed

    private void jMenuItemOuvrirRGBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOuvrirRGBActionPerformed
        JFileChooser choix = new JFileChooser();
	File fichier;
			
	choix.setCurrentDirectory(new File ("."));
	if (choix.showOpenDialog(null) == JFileChooser.APPROVE_OPTION)
	{
            fichier = choix.getSelectedFile();
            if (fichier != null)
            {
                try 
                {
                    imageRGB = new CImageRGB(fichier);
                    slotImagesRGB[activeSlot] = imageRGB;
                    slotImagesNG[activeSlot]  = null;
                    slotLabels[activeSlot]    = fichier.getName();
                    slotTitleLabels[activeSlot].setText(fichier.getName());
                    observer.setCImage(imageRGB);
                    imageNG = null;
                    activeMenusRGB();
                } 
                catch (IOException ex) 
                {
                    System.err.println("Erreur I/O : " + ex.getMessage());
                }
            }
	}
    }//GEN-LAST:event_jMenuItemOuvrirRGBActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // FlatLaf Dark — appliqué par réflexion pour compiler sans le JAR
        try {
            Class<?> laf = Class.forName("com.formdev.flatlaf.FlatDarkLaf");
            UIManager.setLookAndFeel((javax.swing.LookAndFeel) laf.getDeclaredConstructor().newInstance());
        } catch (Exception ignored) { /* JAR absent : thème système utilisé */ }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IsilImageProcessing().setVisible(true);
            }
        });
    }

    public void ClicDetected(UnClicEvent e) 
    {
        if (jCheckBoxMenuItemDessinerPixel.isSelected())
        {   
            try 
            {
                if (imageRGB != null) 
                    imageRGB.setPixel(e.getX(),e.getY(),couleurPinceauRGB);
                if (imageNG != null) 
                    imageNG.setPixel(e.getX(),e.getY(),couleurPinceauNG);
            } 
            catch (CImageRGBException ex) 
            { System.out.println("Erreur RGB : " + ex.getMessage()); }
            catch (CImageNGException ex) 
            { System.out.println("Erreur NG : " + ex.getMessage()); }
        }
    }

    public void SelectLigneDetected(DeuxClicsEvent e) 
    {
        if (jCheckBoxMenuItemDessinerLigne.isSelected())
        {   
            try 
            {
                if (imageRGB != null) 
                    imageRGB.DessineLigne(e.getX1(),e.getY1(),e.getX2(),e.getY2(),couleurPinceauRGB);
                if (imageNG != null) 
                    imageNG.DessineLigne(e.getX1(),e.getY1(),e.getX2(),e.getY2(),couleurPinceauNG);
            } 
            catch (CImageRGBException ex) 
            { System.out.println("Erreur RGB : " + ex.getMessage()); }
            catch (CImageNGException ex) 
            { System.out.println("Erreur NG : " + ex.getMessage()); }
        }
    }

    public void SelectRectDetected(DeuxClicsEvent e) 
    {
        if (jCheckBoxMenuItemDessinerRectangle.isSelected())
        {   
            try 
            {
                if (imageRGB != null)
                    imageRGB.DessineRect(e.getX1(),e.getY1(),e.getX2(),e.getY2(),couleurPinceauRGB);
                if (imageNG != null)
                    imageNG.DessineRect(e.getX1(),e.getY1(),e.getX2(),e.getY2(),couleurPinceauNG);
            } 
            catch (CImageRGBException ex) 
            { System.out.println("Erreur RGB : " + ex.getMessage()); }
            catch (CImageNGException ex) 
            { System.out.println("Erreur NG : " + ex.getMessage()); }
        }
    }

    public void SelectCercleDetected(DeuxClicsEvent e) 
    {
        if (jCheckBoxMenuItemDessinerCercle.isSelected())
        {   
            try 
            {
                if (imageRGB != null)
                    imageRGB.DessineCercle(e.getX1(),e.getY1(),e.getX2(),e.getY2(),couleurPinceauRGB);
                if (imageNG != null)
                    imageNG.DessineCercle(e.getX1(),e.getY1(),e.getX2(),e.getY2(),couleurPinceauNG);
            } 
            catch (CImageRGBException ex) 
            { System.out.println("Erreur RGB : " + ex.getMessage()); }
            catch (CImageNGException ex) 
            { System.out.println("Erreur NG : " + ex.getMessage()); }
        }
    }

    public void SelectCercleFillDetected(DeuxClicsEvent e) 
    {
        if (jCheckBoxMenuItemDessinerCerclePlein.isSelected())
        {   
            try 
            {
                if (imageRGB != null)
                    imageRGB.RemplitCercle(e.getX1(),e.getY1(),e.getX2(),e.getY2(),couleurPinceauRGB);
                if (imageNG != null)
                    imageNG.RemplitCercle(e.getX1(),e.getY1(),e.getX2(),e.getY2(),couleurPinceauNG);
            } 
            catch (CImageRGBException ex) 
            { System.out.println("Erreur RGB : " + ex.getMessage()); }
            catch (CImageNGException ex) 
            { System.out.println("Erreur NG : " + ex.getMessage()); }
        }
    }

    public void SelectRectFillDetected(DeuxClicsEvent e) 
    {
        if (jCheckBoxMenuItemDessinerRectanglePlein.isSelected())
        {   
            try 
            {
                if (imageRGB != null) 
                    imageRGB.RemplitRect(e.getX1(),e.getY1(),e.getX2(),e.getY2(),couleurPinceauRGB);
                if (imageNG != null) 
                    imageNG.RemplitRect(e.getX1(),e.getY1(),e.getX2(),e.getY2(),couleurPinceauNG);
            } 
            catch (CImageRGBException ex) 
            { System.out.println("Erreur RGB : " + ex.getMessage()); }
            catch (CImageNGException ex) 
            { System.out.println("Erreur NG : " + ex.getMessage()); }
        }
    }
    
    // =========================================================
    // HISTOGRAMME — ajout du sous-menu paramètres
    // =========================================================

    private void setupHistogrammeExtraMenu()
    {
        // Paramètres statistiques
        javax.swing.JMenuItem itemParams = new javax.swing.JMenuItem("Afficher les paramètres de l'image");
        itemParams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afficherParametresImage();
            }
        });
        jMenuHistogramme.add(itemParams);

        jMenuHistogramme.addSeparator();

        // Transformations tonales
        addHistoRehaussementItem("Transformation linéaire (sans saturation)",
                                  JDialogRehaussement.Type.LINEAIRE);
        addHistoRehaussementItem("Transformation linéaire avec saturation",
                                  JDialogRehaussement.Type.LINEAIRE_SAT);
        addHistoRehaussementItem("Correction Gamma",
                                  JDialogRehaussement.Type.GAMMA);
        addHistoRehaussementItem("Égalisation de l'histogramme",
                                  JDialogRehaussement.Type.EGALISATION);
        addHistoRehaussementItem("Négatif",
                                  JDialogRehaussement.Type.NEGATIF);
    }

    private void addHistoRehaussementItem(String texte,
                                           final JDialogRehaussement.Type type)
    {
        javax.swing.JMenuItem item = new javax.swing.JMenuItem(texte);
        item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ouvrirRehaussement(type);
            }
        });
        jMenuHistogramme.add(item);
    }

    private void ouvrirRehaussement(JDialogRehaussement.Type type)
    {
        if (imageNG == null) return;
        final int[][] img = getActiveMatrix();
        if (img == null) return;
        new JDialogRehaussement(this, type, img, makeSlotReceiver()).setVisible(true);
    }

    private void afficherParametresImage()
    {
        if (imageNG == null) return;
        try {
            new JDialogParametresImage(this, imageNG.getMatrice()).setVisible(true);
        } catch (CImageNGException ex) {
            System.err.println("Erreur CImageNG : " + ex.getMessage());
        }
    }

    // =========================================================
    // FILTRAGE LINEAIRE — setup du menu et handlers
    // =========================================================

    private void setupFiltrageMenu()
    {
        jMenuFiltrageLineaire = new javax.swing.JMenu("Filtrage linéaire");
        jMenuFiltrageLineaire.setEnabled(false);

        javax.swing.JMenu jMenuFiltrageGlobal = new javax.swing.JMenu("Global");

        javax.swing.JMenuItem itemPasseBasIdeal = new javax.swing.JMenuItem("Passe-bas idéal");
        itemPasseBasIdeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrePasseBasIdealActionPerformed();
            }
        });

        javax.swing.JMenuItem itemPasseHautIdeal = new javax.swing.JMenuItem("Passe-haut idéal");
        itemPasseHautIdeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrePasseHautIdealActionPerformed();
            }
        });

        javax.swing.JMenuItem itemPasseBasButterworth = new javax.swing.JMenuItem("Passe-bas Butterworth");
        itemPasseBasButterworth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrePasseBasButterworthActionPerformed();
            }
        });

        javax.swing.JMenuItem itemPasseHautButterworth = new javax.swing.JMenuItem("Passe-haut Butterworth");
        itemPasseHautButterworth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrePasseHautButterworthActionPerformed();
            }
        });

        jMenuFiltrageGlobal.add(itemPasseBasIdeal);
        jMenuFiltrageGlobal.add(itemPasseHautIdeal);
        jMenuFiltrageGlobal.add(itemPasseBasButterworth);
        jMenuFiltrageGlobal.add(itemPasseHautButterworth);

        jMenuFiltrageLineaire.add(jMenuFiltrageGlobal);

        // --- Sous-menu Local ---
        javax.swing.JMenu jMenuFiltrageLocal = new javax.swing.JMenu("Local");

        javax.swing.JMenuItem itemMoyenneur = new javax.swing.JMenuItem("Filtre moyenneur");
        itemMoyenneur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtreLocalMoyenneurActionPerformed();
            }
        });

        javax.swing.JMenuItem itemMasqueConvolution = new javax.swing.JMenuItem("Masque de convolution");
        itemMasqueConvolution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtreLocalMasqueConvolutionActionPerformed();
            }
        });

        jMenuFiltrageLocal.add(itemMoyenneur);
        jMenuFiltrageLocal.add(itemMasqueConvolution);
        jMenuFiltrageLineaire.add(jMenuFiltrageLocal);

        jMenuBar1.add(jMenuFiltrageLineaire);
    }

    private int[][] getActiveMatrix()
    {
        if (imageNG == null) return null;
        try { return imageNG.getMatrice(); }
        catch (CImageNGException ex) { return null; }
    }

    private SlotReceiver makeSlotReceiver()
    {
        return new SlotReceiver() {
            public void accept(int[][] m, String l) { afficherImageResultat(m, l); }
        };
    }

    private SlotData[] buildMasqueSlots()
    {
        List<SlotData> list = new ArrayList<SlotData>();
        for (int i = 0; i < NB_SLOTS; i++) {
            if (slotImagesNG[i] != null) {
                try {
                    String nom = (slotLabels[i] != null) ? slotLabels[i] : "Slot " + (i + 1);
                    list.add(new SlotData(slotImagesNG[i].getMatrice(), nom));
                } catch (CImageNGException ignored) {}
            }
        }
        return list.toArray(new SlotData[0]);
    }

    private void afficherImageResultat(int[][] matrice, String titre)
    {
        int cible = -1;
        for (int i = 0; i < NB_SLOTS; i++)
            if (slotImagesNG[i] == null && slotImagesRGB[i] == null) { cible = i; break; }
        if (cible == -1) cible = (activeSlot + 1) % NB_SLOTS;
        placeInSlot(cible, matrice, titre);
    }

    private void filtrePasseBasIdealActionPerformed()
    {
        if (imageNG == null) return;
        final int[][] img = getActiveMatrix();
        if (img == null) return;
        JPanel params = new JPanel(new FlowLayout(FlowLayout.LEFT, 6, 2));
        params.add(new JLabel("Fréquence de coupure :"));
        final JSpinner sp = new JSpinner(new SpinnerNumberModel(30, 1, 999, 1));
        params.add(sp);
        JDialogTraitement.ComputeAction action = new JDialogTraitement.ComputeAction() {
            public int[][] compute() throws Exception {
                return FiltrageLineaireGlobal.filtrePasseBasIdeal(img, (Integer) sp.getValue());
            }
        };
        new JDialogTraitement(this, "Passe-bas idéal", img, params, action, makeSlotReceiver()).setVisible(true);
    }

    private void filtrePasseHautIdealActionPerformed()
    {
        if (imageNG == null) return;
        final int[][] img = getActiveMatrix();
        if (img == null) return;
        JPanel params = new JPanel(new FlowLayout(FlowLayout.LEFT, 6, 2));
        params.add(new JLabel("Fréquence de coupure :"));
        final JSpinner sp = new JSpinner(new SpinnerNumberModel(30, 1, 999, 1));
        params.add(sp);
        JDialogTraitement.ComputeAction action = new JDialogTraitement.ComputeAction() {
            public int[][] compute() throws Exception {
                return FiltrageLineaireGlobal.filtrePasseHautIdeal(img, (Integer) sp.getValue());
            }
        };
        new JDialogTraitement(this, "Passe-haut idéal", img, params, action, makeSlotReceiver()).setVisible(true);
    }

    private void filtrePasseBasButterworthActionPerformed()
    {
        if (imageNG == null) return;
        final int[][] img = getActiveMatrix();
        if (img == null) return;
        JPanel params = new JPanel(new FlowLayout(FlowLayout.LEFT, 6, 2));
        params.add(new JLabel("Fréquence coupure :"));
        final JSpinner spFc = new JSpinner(new SpinnerNumberModel(30, 1, 999, 1));
        params.add(spFc);
        params.add(new JLabel("  Ordre :"));
        final JSpinner spOrdre = new JSpinner(new SpinnerNumberModel(2, 1, 20, 1));
        params.add(spOrdre);
        JDialogTraitement.ComputeAction action = new JDialogTraitement.ComputeAction() {
            public int[][] compute() throws Exception {
                return FiltrageLineaireGlobal.filtrePasseBasButterworth(
                    img, (Integer) spFc.getValue(), (Integer) spOrdre.getValue());
            }
        };
        new JDialogTraitement(this, "Passe-bas Butterworth", img, params, action, makeSlotReceiver()).setVisible(true);
    }

    private void filtrePasseHautButterworthActionPerformed()
    {
        if (imageNG == null) return;
        final int[][] img = getActiveMatrix();
        if (img == null) return;
        JPanel params = new JPanel(new FlowLayout(FlowLayout.LEFT, 6, 2));
        params.add(new JLabel("Fréquence coupure :"));
        final JSpinner spFc = new JSpinner(new SpinnerNumberModel(30, 1, 999, 1));
        params.add(spFc);
        params.add(new JLabel("  Ordre :"));
        final JSpinner spOrdre = new JSpinner(new SpinnerNumberModel(2, 1, 20, 1));
        params.add(spOrdre);
        JDialogTraitement.ComputeAction action = new JDialogTraitement.ComputeAction() {
            public int[][] compute() throws Exception {
                return FiltrageLineaireGlobal.filtrePasseHautButterworth(
                    img, (Integer) spFc.getValue(), (Integer) spOrdre.getValue());
            }
        };
        new JDialogTraitement(this, "Passe-haut Butterworth", img, params, action, makeSlotReceiver()).setVisible(true);
    }

    private void filtreLocalMoyenneurActionPerformed()
    {
        if (imageNG == null) return;
        final int[][] img = getActiveMatrix();
        if (img == null) return;
        JPanel params = new JPanel(new FlowLayout(FlowLayout.LEFT, 6, 2));
        params.add(new JLabel("Taille masque :"));
        final JSpinner sp = new JSpinner(new SpinnerNumberModel(3, 1, 99, 2));
        params.add(sp);
        JDialogTraitement.ComputeAction action = new JDialogTraitement.ComputeAction() {
            public int[][] compute() throws Exception {
                return FiltrageLineaireLocal.filtreMoyenneur(img, (Integer) sp.getValue());
            }
        };
        new JDialogTraitement(this, "Filtre moyenneur", img, params, action, makeSlotReceiver()).setVisible(true);
    }

    private void filtreLocalMasqueConvolutionActionPerformed()
    {
        if (imageNG == null) return;
        final int[][] img = getActiveMatrix();
        if (img == null) return;
        final JDialogTraitement.MasquePanel masquePanel = new JDialogTraitement.MasquePanel();
        JDialogTraitement.ComputeAction action = new JDialogTraitement.ComputeAction() {
            public int[][] compute() throws Exception {
                double[][] m = masquePanel.getMasque();
                return FiltrageLineaireLocal.filtreMasqueConvolution(img, m);
            }
        };
        new JDialogTraitement(this, "Masque de convolution", img, masquePanel, action, makeSlotReceiver()).setVisible(true);
    }

    // =========================================================
    // MORPHOLOGIE ELEMENTAIRE — setup du menu et handlers
    // =========================================================

    private void setupMorphoMenu()
    {
        jMenuTraitementNonLineaire = new javax.swing.JMenu("Traitement non-linéaire");
        jMenuTraitementNonLineaire.setEnabled(false);

        javax.swing.JMenu jMenuMorphoElementaire = new javax.swing.JMenu("Elementaire");

        javax.swing.JMenuItem itemErosion = new javax.swing.JMenuItem("Erosion");
        itemErosion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                morphoErosionActionPerformed();
            }
        });

        javax.swing.JMenuItem itemDilatation = new javax.swing.JMenuItem("Dilatation");
        itemDilatation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                morphoDilatationActionPerformed();
            }
        });

        javax.swing.JMenuItem itemOuverture = new javax.swing.JMenuItem("Ouverture");
        itemOuverture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                morphoOuvertureActionPerformed();
            }
        });

        javax.swing.JMenuItem itemFermeture = new javax.swing.JMenuItem("Fermeture");
        itemFermeture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                morphoFermetureActionPerformed();
            }
        });

        jMenuMorphoElementaire.add(itemErosion);
        jMenuMorphoElementaire.add(itemDilatation);
        jMenuMorphoElementaire.add(itemOuverture);
        jMenuMorphoElementaire.add(itemFermeture);

        jMenuTraitementNonLineaire.add(jMenuMorphoElementaire);

        // --- Sous-menu Complexe ---
        javax.swing.JMenu jMenuMorphoComplexe = new javax.swing.JMenu("Complexe");

        javax.swing.JMenuItem itemDilatGeo = new javax.swing.JMenuItem("Dilatation géodésique");
        itemDilatGeo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                morphoDilatationGeodesique();
            }
        });

        javax.swing.JMenuItem itemReconGeo = new javax.swing.JMenuItem("Reconstruction géodésique");
        itemReconGeo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                morphoReconstructionGeodesique();
            }
        });

        javax.swing.JMenuItem itemMedian = new javax.swing.JMenuItem("Filtre médian");
        itemMedian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                morphoFiltreMedian();
            }
        });

        jMenuMorphoComplexe.add(itemDilatGeo);
        jMenuMorphoComplexe.add(itemReconGeo);
        jMenuMorphoComplexe.add(itemMedian);

        jMenuTraitementNonLineaire.add(jMenuMorphoComplexe);
        jMenuBar1.add(jMenuTraitementNonLineaire);
    }

    // -----------------------------------------------------------------------
    // Menu Contours → Linéaire
    // -----------------------------------------------------------------------

    private void setupContoursMenu()
    {
        jMenuContours = new javax.swing.JMenu("Contours");
        jMenuContours.setEnabled(false);

        javax.swing.JMenu jMenuContoursLineaire = new javax.swing.JMenu("Linéaire");

        addContourItem(jMenuContoursLineaire, "Filtre de Prewitt",
            isilimageprocessing.Dialogues.JDialogContourLineaire.Type.GRADIENT_PREWITT, 1);
        addContourItem(jMenuContoursLineaire, "Filtre de Sobel",
            isilimageprocessing.Dialogues.JDialogContourLineaire.Type.GRADIENT_SOBEL, 1);
        jMenuContoursLineaire.addSeparator();
        addContourItem(jMenuContoursLineaire, "Laplacien4",
            isilimageprocessing.Dialogues.JDialogContourLineaire.Type.LAPLACIEN4, 0);
        addContourItem(jMenuContoursLineaire, "Laplacien8",
            isilimageprocessing.Dialogues.JDialogContourLineaire.Type.LAPLACIEN8, 0);

        jMenuContours.add(jMenuContoursLineaire);

        // ---- Sous-menu Non-linéaire ----
        javax.swing.JMenu jMenuContoursNL = new javax.swing.JMenu("Non-linéaire");

        addContourNLItem(jMenuContoursNL, "Gradient d'érosion",
            isilimageprocessing.Dialogues.JDialogContourNonLineaire.Type.GRADIENT_EROSION);
        addContourNLItem(jMenuContoursNL, "Gradient de dilatation",
            isilimageprocessing.Dialogues.JDialogContourNonLineaire.Type.GRADIENT_DILATATION);
        addContourNLItem(jMenuContoursNL, "Gradient de Beucher",
            isilimageprocessing.Dialogues.JDialogContourNonLineaire.Type.GRADIENT_BEUCHER);
        addContourNLItem(jMenuContoursNL, "Laplacien non-linéaire",
            isilimageprocessing.Dialogues.JDialogContourNonLineaire.Type.LAPLACIEN_NL);

        jMenuContours.add(jMenuContoursNL);
        jMenuBar1.add(jMenuContours);
    }

    private void addContourItem(javax.swing.JMenu menu, String texte,
                                 final isilimageprocessing.Dialogues.JDialogContourLineaire.Type type,
                                 final int dir)
    {
        javax.swing.JMenuItem item = new javax.swing.JMenuItem(texte);
        final String titre = texte;
        item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ouvrirContourLineaire(titre, type, dir);
            }
        });
        menu.add(item);
    }

    private void ouvrirContourLineaire(String titre,
                                        isilimageprocessing.Dialogues.JDialogContourLineaire.Type type,
                                        int dir)
    {
        if (imageNG == null) return;
        final int[][] img = getActiveMatrix();
        if (img == null) return;
        new isilimageprocessing.Dialogues.JDialogContourLineaire(
            this, titre, type, dir, img, makeSlotReceiver()).setVisible(true);
    }

    private void addContourNLItem(javax.swing.JMenu menu, String texte,
                                   final isilimageprocessing.Dialogues.JDialogContourNonLineaire.Type type)
    {
        javax.swing.JMenuItem item = new javax.swing.JMenuItem(texte);
        final String titre = texte;
        item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ouvrirContourNonLineaire(titre, type);
            }
        });
        menu.add(item);
    }

    private void ouvrirContourNonLineaire(String titre,
                                           isilimageprocessing.Dialogues.JDialogContourNonLineaire.Type type)
    {
        if (imageNG == null) return;
        final int[][] img = getActiveMatrix();
        if (img == null) return;
        new isilimageprocessing.Dialogues.JDialogContourNonLineaire(
            this, titre, type, img, makeSlotReceiver()).setVisible(true);
    }

    // -----------------------------------------------------------------------
    // Menu Seuillage
    // -----------------------------------------------------------------------

    private void setupSeuillageMenu()
    {
        jMenuSeuillage = new javax.swing.JMenu("Seuillage");
        jMenuSeuillage.setEnabled(false);

        addSeuilItem("Seuillage simple",
            isilimageprocessing.Dialogues.JDialogSeuillage.Type.SIMPLE);
        addSeuilItem("Seuillage double",
            isilimageprocessing.Dialogues.JDialogSeuillage.Type.DOUBLE);
        addSeuilItem("Seuillage automatique",
            isilimageprocessing.Dialogues.JDialogSeuillage.Type.AUTOMATIQUE);

        jMenuBar1.add(jMenuSeuillage);
    }

    private void addSeuilItem(String texte,
                               final isilimageprocessing.Dialogues.JDialogSeuillage.Type type)
    {
        javax.swing.JMenuItem item = new javax.swing.JMenuItem(texte);
        item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ouvrirSeuillage(type);
            }
        });
        jMenuSeuillage.add(item);
    }

    private void ouvrirSeuillage(isilimageprocessing.Dialogues.JDialogSeuillage.Type type)
    {
        if (imageNG == null) return;
        final int[][] img = getActiveMatrix();
        if (img == null) return;
        new isilimageprocessing.Dialogues.JDialogSeuillage(
            this, type, img, makeSlotReceiver()).setVisible(true);
    }

    // -----------------------------------------------------------------------
    // Menu Applications
    // -----------------------------------------------------------------------

    private void setupApplicationsMenu()
    {
        jMenuApplications = new javax.swing.JMenu("Applications");

        String[] noms = {
            "1. Réduction du bruit",
            "2. Égalisation histogramme (Lena)",
            "3. Petits pois (bleus et rouges)",
            "4. Balanes (grandes et petites)",
            "5. Segmentation outils",
            "6. Vaisseau spatial",
            "7. Contours des tartines"
        };

        for (int k = 0; k < noms.length; k++) {
            javax.swing.JMenuItem item = new javax.swing.JMenuItem(noms[k]);
            final int idx = k;
            item.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent e) {
                    switch (idx) {
                        case 0: appEx1ReductionBruit();       break;
                        case 1: appEx2EgalisationRGB();       break;
                        case 2: appEx3PetitsPois();           break;
                        case 3: appEx4Balanes();              break;
                        case 4: appEx5SegmentationOutils();   break;
                        case 5: appEx6VaisseauSpatial();      break;
                        case 6: appEx7ContoursTartines();     break;
                    }
                }
            });
            jMenuApplications.add(item);
        }

        jMenuBar1.add(jMenuApplications);
    }

    /** Cherche un fichier image dans src/ImagesEtape5/. */
    java.io.File trouverImage(String nom)
    {
        java.io.File f = new java.io.File("src/ImagesEtape5", nom);
        if (f.exists()) return f;
        return null;
    }

    void imageNonTrouvee(String nom)
    {
        JOptionPane.showMessageDialog(this, "Image non trouvée : " + nom,
            "Image manquante", JOptionPane.ERROR_MESSAGE);
    }

    // ---- Exercice 1 : Réduction du bruit ----
    private void appEx1ReductionBruit()     { new AppEx1ReductionBruit(this).executer(); }

    // ---- Exercice 2 : Égalisation histogramme RGB ----
    private void appEx2EgalisationRGB()     { new AppEx2EgalisationRGB(this).executer(); }

    // ---- Exercice 3 : Petits pois ----
    private void appEx3PetitsPois()         { new AppEx3PetitsPois(this).executer(); }

    // ---- Exercice 4 : Balanes ----
    private void appEx4Balanes()            { new AppEx4Balanes(this).executer(); }

    // ---- Exercice 5 : Segmentation outils ----
    private void appEx5SegmentationOutils() { new AppEx5SegmentationOutils(this).executer(); }

    // ---- Exercice 6 : Vaisseau spatial ----
    private void appEx6VaisseauSpatial()    { new AppEx6VaisseauSpatial(this).executer(); }

    // ---- Exercice 7 : Contours des tartines ----
    private void appEx7ContoursTartines()   { new AppEx7ContoursTartines(this).executer(); }

    // -----------------------------------------------------------------------

    private void morphoErosionActionPerformed()
    {
        if (imageNG == null) return;
        final int[][] img = getActiveMatrix();
        if (img == null) return;
        JPanel params = new JPanel(new FlowLayout(FlowLayout.LEFT, 6, 2));
        params.add(new JLabel("Taille masque :"));
        final JSpinner sp = new JSpinner(new SpinnerNumberModel(3, 1, 99, 2));
        params.add(sp);
        JDialogTraitement.ComputeAction action = new JDialogTraitement.ComputeAction() {
            public int[][] compute() throws Exception {
                return MorphoElementaire.erosion(img, (Integer) sp.getValue());
            }
        };
        new JDialogTraitement(this, "Erosion", img, params, action, makeSlotReceiver()).setVisible(true);
    }

    private void morphoDilatationActionPerformed()
    {
        if (imageNG == null) return;
        final int[][] img = getActiveMatrix();
        if (img == null) return;
        JPanel params = new JPanel(new FlowLayout(FlowLayout.LEFT, 6, 2));
        params.add(new JLabel("Taille masque :"));
        final JSpinner sp = new JSpinner(new SpinnerNumberModel(3, 1, 99, 2));
        params.add(sp);
        JDialogTraitement.ComputeAction action = new JDialogTraitement.ComputeAction() {
            public int[][] compute() throws Exception {
                return MorphoElementaire.dilatation(img, (Integer) sp.getValue());
            }
        };
        new JDialogTraitement(this, "Dilatation", img, params, action, makeSlotReceiver()).setVisible(true);
    }

    private void morphoOuvertureActionPerformed()
    {
        if (imageNG == null) return;
        final int[][] img = getActiveMatrix();
        if (img == null) return;
        JPanel params = new JPanel(new FlowLayout(FlowLayout.LEFT, 6, 2));
        params.add(new JLabel("Taille masque :"));
        final JSpinner sp = new JSpinner(new SpinnerNumberModel(3, 1, 99, 2));
        params.add(sp);
        JDialogTraitement.ComputeAction action = new JDialogTraitement.ComputeAction() {
            public int[][] compute() throws Exception {
                return MorphoElementaire.ouverture(img, (Integer) sp.getValue());
            }
        };
        new JDialogTraitement(this, "Ouverture", img, params, action, makeSlotReceiver()).setVisible(true);
    }

    private void morphoFermetureActionPerformed()
    {
        if (imageNG == null) return;
        final int[][] img = getActiveMatrix();
        if (img == null) return;
        JPanel params = new JPanel(new FlowLayout(FlowLayout.LEFT, 6, 2));
        params.add(new JLabel("Taille masque :"));
        final JSpinner sp = new JSpinner(new SpinnerNumberModel(3, 1, 99, 2));
        params.add(sp);
        JDialogTraitement.ComputeAction action = new JDialogTraitement.ComputeAction() {
            public int[][] compute() throws Exception {
                return MorphoElementaire.fermeture(img, (Integer) sp.getValue());
            }
        };
        new JDialogTraitement(this, "Fermeture", img, params, action, makeSlotReceiver()).setVisible(true);
    }

    // =========================================================
    // MORPHOLOGIE COMPLEXE — helpers et handlers
    // =========================================================

    /**
     * Ouvre un JFileChooser pour que l'utilisateur choisisse une image NG
     * qui servira de masque géodésique. Retourne la matrice ou null si annulé.
     */
    private int[][] chargerMasqueGeodesique()
    {
        JFileChooser choix = new JFileChooser();
        choix.setCurrentDirectory(new File("."));
        choix.setDialogTitle("Choisir le masque géodésique (image NG)");
        if (choix.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) return null;
        File fichier = choix.getSelectedFile();
        if (fichier == null) return null;
        try
        {
            CImageNG masque = new CImageNG(fichier);
            return masque.getMatrice();
        }
        catch (IOException ex)
        {
            JOptionPane.showMessageDialog(this,
                "Erreur de lecture : " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        catch (CImageNGException ex)
        {
            JOptionPane.showMessageDialog(this,
                "Erreur image : " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        return null;
    }

    private void morphoDilatationGeodesique()
    {
        if (imageNG == null) return;
        try
        {
            String markerNom = (slotLabels[activeSlot] != null) ? slotLabels[activeSlot] : "Slot " + (activeSlot + 1);
            SlotData marker  = new SlotData(imageNG.getMatrice(), markerNom);
            new JDialogGeodesique(IsilImageProcessing.this,
                JDialogGeodesique.Type.DILATATION, marker, buildMasqueSlots(), makeSlotReceiver()).setVisible(true);
        }
        catch (CImageNGException ex) { System.err.println("Erreur CImageNG : " + ex.getMessage()); }
    }

    private void morphoReconstructionGeodesique()
    {
        if (imageNG == null) return;
        try
        {
            String markerNom = (slotLabels[activeSlot] != null) ? slotLabels[activeSlot] : "Slot " + (activeSlot + 1);
            SlotData marker  = new SlotData(imageNG.getMatrice(), markerNom);
            new JDialogGeodesique(IsilImageProcessing.this,
                JDialogGeodesique.Type.RECONSTRUCTION, marker, buildMasqueSlots(), makeSlotReceiver()).setVisible(true);
        }
        catch (CImageNGException ex) { System.err.println("Erreur CImageNG : " + ex.getMessage()); }
    }

    private void morphoFiltreMedian()
    {
        if (imageNG == null) return;
        final int[][] img = getActiveMatrix();
        if (img == null) return;
        JPanel params = new JPanel(new FlowLayout(FlowLayout.LEFT, 6, 2));
        params.add(new JLabel("Taille masque :"));
        final JSpinner sp = new JSpinner(new SpinnerNumberModel(3, 1, 99, 2));
        params.add(sp);
        JDialogTraitement.ComputeAction action = new JDialogTraitement.ComputeAction() {
            public int[][] compute() throws Exception {
                return MorphoComplexe.filtreMedian(img, (Integer) sp.getValue());
            }
        };
        new JDialogTraitement(this, "Filtre médian", img, params, action, makeSlotReceiver()).setVisible(true);
    }

    // =========================================================
    // SYSTÈME DE SLOTS
    // =========================================================

    private void setupSlots()
    {
        // Grille 2×2 pour 4 slots
        JPanel mainSlotsPanel = new JPanel(new GridLayout(2, 2, 8, 8));
        mainSlotsPanel.setBorder(BorderFactory.createEmptyBorder(8, 8, 8, 8));

        for (int i = 0; i < NB_SLOTS; i++)
        {
            final int idx = i;

            // Observer (affichage + dessin)
            slotObservers[i] = new JLabelBeanCImage();
            slotObservers[i].addClicListener(this);
            slotObservers[i].addSelectLigneListener(this);
            slotObservers[i].addSelectRectListener(this);
            slotObservers[i].addSelectRectFillListener(this);
            slotObservers[i].addSelectCercleListener(this);
            slotObservers[i].addSelectCercleFillListener(this);
            slotObservers[i].setMode(JLabelBeanCImage.INACTIF);

            // Label titre (clic = activer, drag = déplacer)
            slotTitleLabels[i] = new JLabel("—", SwingConstants.CENTER);
            slotTitleLabels[i].setFont(slotTitleLabels[i].getFont().deriveFont(11f));
            slotTitleLabels[i].setBorder(BorderFactory.createEmptyBorder(2, 2, 2, 2));
            slotTitleLabels[i].setCursor(Cursor.getPredefinedCursor(Cursor.MOVE_CURSOR));
            slotTitleLabels[i].setToolTipText("Cliquez pour activer · Glissez pour déplacer");

            // Clic sur le titre = activer le slot
            slotTitleLabels[i].addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent e) {
                    setActiveSlot(idx);
                }
            });

            // --- DRAG SOURCE : glisser depuis le titre ---
            slotTitleLabels[i].setTransferHandler(new TransferHandler()
            {
                @Override
                public int getSourceActions(JComponent c) {
                    return (slotImagesNG[idx] != null) ? COPY : NONE;
                }
                @Override
                protected Transferable createTransferable(JComponent c)
                {
                    if (slotImagesNG[idx] == null) return null;
                    try {
                        final SlotData sd = new SlotData(slotImagesNG[idx].getMatrice(), slotLabels[idx]);
                        return new Transferable() {
                            public DataFlavor[] getTransferDataFlavors() { return new DataFlavor[]{ SlotData.FLAVOR }; }
                            public boolean isDataFlavorSupported(DataFlavor f) { return SlotData.FLAVOR.equals(f); }
                            public Object getTransferData(DataFlavor f) { return sd; }
                        };
                    } catch (CImageNGException e) { return null; }
                }
            });
            slotTitleLabels[i].addMouseMotionListener(new MouseMotionAdapter() {
                public void mouseDragged(MouseEvent e) {
                    JComponent c = (JComponent) e.getSource();
                    c.getTransferHandler().exportAsDrag(c, e, TransferHandler.COPY);
                }
            });

            // Bouton supprimer (✕) placé à droite du titre
            JButton btnSupprimer = new JButton("✕");
            btnSupprimer.setFont(btnSupprimer.getFont().deriveFont(java.awt.Font.BOLD, 11f));
            btnSupprimer.setForeground(new Color(180, 50, 50));
            btnSupprimer.setToolTipText("Supprimer l'image de ce slot");
            btnSupprimer.setMargin(new java.awt.Insets(0, 5, 0, 5));
            btnSupprimer.setFocusPainted(false);
            btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    supprimerSlot(idx);
                }
            });

            JPanel headerPanel = new JPanel(new BorderLayout(0, 0));
            headerPanel.add(slotTitleLabels[i], BorderLayout.CENTER);
            headerPanel.add(btnSupprimer, BorderLayout.EAST);

            slotScrollPanes[i] = new JScrollPane(slotObservers[i]);
            slotScrollPanes[i].setPreferredSize(new Dimension(480, 380));

            slotPanels[i] = new JPanel(new BorderLayout(2, 2));
            slotPanels[i].add(headerPanel, BorderLayout.NORTH);
            slotPanels[i].add(slotScrollPanes[i], BorderLayout.CENTER);

            // Clic sur le panel = activer le slot
            slotPanels[i].addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent e) {
                    setActiveSlot(idx);
                }
            });

            // --- DROP TARGET : recevoir une image glissée ---
            slotPanels[i].setTransferHandler(new TransferHandler()
            {
                @Override
                public boolean canImport(TransferSupport support) {
                    return support.isDataFlavorSupported(SlotData.FLAVOR);
                }
                @Override
                public boolean importData(TransferSupport support)
                {
                    try {
                        SlotData sd = (SlotData) support.getTransferable().getTransferData(SlotData.FLAVOR);
                        placeInSlot(idx, sd.matrix, sd.label);
                        return true;
                    } catch (Exception ex) { return false; }
                }
            });

            mainSlotsPanel.add(slotPanels[i]);
        }

        getContentPane().removeAll();
        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(new JScrollPane(mainSlotsPanel), BorderLayout.CENTER);

        observer = slotObservers[0];
        setActiveSlot(0);

        setSize(1100, 950);
        setLocationRelativeTo(null);
        revalidate();
        repaint();
    }

    /** Place une image int[][] dans un slot donné et met à jour l'affichage. */
    void placeInSlot(int slotIdx, int[][] matrix, String label)
    {
        try
        {
            CImageNG img = new CImageNG(matrix);
            slotImagesNG[slotIdx]  = img;
            slotImagesRGB[slotIdx] = null;
            slotLabels[slotIdx]    = label;
            String aff = (label != null && label.length() > 26) ? label.substring(0, 24) + "…" : (label != null ? label : "—");
            slotTitleLabels[slotIdx].setText("<html><center>" + aff + "</center></html>");
            slotObservers[slotIdx].setCImage(img);
            if (slotIdx == activeSlot) setActiveSlot(activeSlot);
        }
        catch (CImageNGException ex) { System.err.println("Erreur slot : " + ex.getMessage()); }
    }

    /** Place une CImageRGB dans un slot donné et met à jour l'affichage. */
    void placeInSlotRGB(int slotIdx, CImageRGB img, String label)
    {
        slotImagesRGB[slotIdx] = img;
        slotImagesNG[slotIdx]  = null;
        slotLabels[slotIdx]    = label;
        String aff = (label != null && label.length() > 26) ? label.substring(0, 24) + "…" : (label != null ? label : "—");
        slotTitleLabels[slotIdx].setText("<html><center>" + aff + "</center></html>");
        slotObservers[slotIdx].setCImage(img);
        if (slotIdx == activeSlot) setActiveSlot(activeSlot);
    }

    /** Vide un slot : efface l'image, réinitialise le titre et l'affichage. */
    void supprimerSlot(int idx)
    {
        slotImagesNG[idx]  = null;
        slotImagesRGB[idx] = null;
        slotLabels[idx]    = null;
        slotTitleLabels[idx].setText("—");

        // Recréer un observer vierge (JLabelBeanCImage n'a pas de méthode clear)
        JLabelBeanCImage nouvelObs = new JLabelBeanCImage();
        nouvelObs.setMode(JLabelBeanCImage.INACTIF);
        nouvelObs.addClicListener(this);
        nouvelObs.addSelectLigneListener(this);
        nouvelObs.addSelectRectListener(this);
        nouvelObs.addSelectRectFillListener(this);
        nouvelObs.addSelectCercleListener(this);
        nouvelObs.addSelectCercleFillListener(this);
        slotObservers[idx] = nouvelObs;
        slotScrollPanes[idx].setViewportView(nouvelObs);
        slotScrollPanes[idx].revalidate();

        if (idx == activeSlot) {
            imageNG  = null;
            imageRGB = null;
            observer = slotObservers[idx];
        }
        setActiveSlot(idx);
    }

    void setActiveSlot(int index)
    {
        activeSlot = index;
        observer   = slotObservers[index];
        imageNG    = slotImagesNG[index];
        imageRGB   = slotImagesRGB[index];

        // Réinitialise les modes de dessin
        jCheckBoxMenuItemDessinerPixel.setSelected(false);
        jCheckBoxMenuItemDessinerLigne.setSelected(false);
        jCheckBoxMenuItemDessinerRectangle.setSelected(false);
        jCheckBoxMenuItemDessinerRectanglePlein.setSelected(false);
        jCheckBoxMenuItemDessinerCercle.setSelected(false);
        jCheckBoxMenuItemDessinerCerclePlein.setSelected(false);
        for (int i = 0; i < NB_SLOTS; i++)
            slotObservers[i].setMode(JLabelBeanCImage.INACTIF);

        // Bordures : bleu épais sur le slot actif, gris sur les autres
        for (int i = 0; i < NB_SLOTS; i++)
        {
            String nom = "Slot " + (i + 1);
            if (i == activeSlot)
                slotPanels[i].setBorder(BorderFactory.createTitledBorder(
                    BorderFactory.createLineBorder(new Color(0, 120, 215), 3), nom + "  ★ actif"));
            else
                slotPanels[i].setBorder(BorderFactory.createTitledBorder(
                    BorderFactory.createLineBorder(Color.LIGHT_GRAY, 1), nom));
        }

        // Met à jour les menus selon l'image du slot actif
        if (imageNG != null)        activeMenusNG();
        else if (imageRGB != null)  activeMenusRGB();
        else
        {
            jMenuDessiner.setEnabled(false);
            jMenuFourier.setEnabled(false);
            jMenuHistogramme.setEnabled(false);
            jMenuFiltrageLineaire.setEnabled(false);
            jMenuTraitementNonLineaire.setEnabled(false);
            jMenuContours.setEnabled(false);
            jMenuSeuillage.setEnabled(false);
        }
    }

    /**
     * Propose à l'utilisateur de choisir le masque géodésique parmi les slots
     * non vides (NG uniquement), avec une option "Charger depuis un fichier".
     */
    private SlotData choisirMasqueGeodesique(String titre)
    {
        List<Integer> slotsDisponibles = new ArrayList<Integer>();
        List<String>  options          = new ArrayList<String>();
        for (int i = 0; i < NB_SLOTS; i++)
        {
            if (slotImagesNG[i] != null)
            {
                slotsDisponibles.add(i);
                String nom = slotLabels[i] != null ? slotLabels[i] : "—";
                options.add("Slot " + (i + 1) + " : " + nom);
            }
        }
        options.add("Charger depuis un fichier...");

        Object[] opt = options.toArray();
        int choix = JOptionPane.showOptionDialog(this,
            "Choisissez le masque géodésique :", titre,
            JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,
            null, opt, opt[0]);

        if (choix < 0) return null;

        if (choix == slotsDisponibles.size())
        {
            int[][] m = chargerMasqueGeodesique();
            return (m != null) ? new SlotData(m, "fichier") : null;
        }

        try
        {
            int idx = slotsDisponibles.get(choix);
            String nom = slotLabels[idx] != null ? slotLabels[idx] : "Slot " + (idx + 1);
            return new SlotData(slotImagesNG[idx].getMatrice(), nom);
        }
        catch (CImageNGException ex)
        {
            System.err.println("Erreur CImageNG : " + ex.getMessage());
            return null;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupDessiner;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemDessinerCercle;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemDessinerCerclePlein;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemDessinerLigne;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemDessinerPixel;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemDessinerRectangle;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemDessinerRectanglePlein;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuDessiner;
    private javax.swing.JMenu jMenuFourier;
    private javax.swing.JMenu jMenuFourierAfficher;
    private javax.swing.JMenu jMenuHistogramme;
    private javax.swing.JMenuItem jMenuHistogrammeAfficher;
    private javax.swing.JMenu jMenuImage;
    private javax.swing.JMenuItem jMenuItemCouleurPinceau;
    private javax.swing.JMenuItem jMenuItemEnregistrerSous;
    private javax.swing.JMenuItem jMenuItemFourierAfficherModule;
    private javax.swing.JMenuItem jMenuItemFourierAfficherPartieImaginaire;
    private javax.swing.JMenuItem jMenuItemFourierAfficherPartieReelle;
    private javax.swing.JMenuItem jMenuItemFourierAfficherPhase;
    private javax.swing.JMenuItem jMenuItemNouvelleNG;
    private javax.swing.JMenuItem jMenuItemNouvelleRGB;
    private javax.swing.JMenuItem jMenuItemOuvrirNG;
    private javax.swing.JMenuItem jMenuItemOuvrirRGB;
    private javax.swing.JMenu jMenuNouvelle;
    private javax.swing.JMenu jMenuOuvrir;
    private javax.swing.JMenuItem jMenuQuitter;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
    
}
